apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webproject
  labels:
    app: webapp
    deploymentconfig: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
        deploymentconfig: webapp
    spec:
      containers:
      - name: webapp
        image: image-registry.openshift-image-registry.svc:5000/webproject/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 50Mi
            cpu: 200m
          limits:
            memory: 80Mi
            cpu: 500m
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-credential
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credential
              key: password
        - name: DATABASE_INSTANCE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_instance
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webproject
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
---
apiVersion: v1
kind: Route
metadata:
  name: webapp-route
  namespace: webproject
  labels:
    app: webapp
spec:
  host: webapp-name-webproject.apps.shared-na4.na4.openshift.opentlc.com
  to:
    kind: Service
    name: webapp-service
    weight: 100
  port:
    targetPort: 5000-tcp
  wildcardPolicy: None
