apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: blog-post
  namespace: webproject
  labels:
    strimzi.io/cluster: kafkaserver1
    app: msa-amq-stream
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
