apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: webproject
  labels:
    app: webapp
    deploymentconfig: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: webapp
  minReplicas: 1 
  maxReplicas: 5 
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
